name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    container: osrf/ros:humble-desktop
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up ROS 2 Humble
        run: |
          sudo apt update  
          sudo apt upgrade -y 
          sudo apt install software-properties-common -y 
          sudo apt install python3-pip -y
          source /opt/ros/humble/setup.bash
      
      - name: Install Python Dependencies
        run: |
          python3 -m pip install matplotlib numpy

      - name: Set up Source Directory
        run: |
          mkdir src
          mv cc_msgs src/
          mv power_energy_propogation/ src/
      
      - name: Colcon Build cc_msgs
        run: |
          colcon build --packages-select cc_msgs --symlink-install
          . install/local_setup.bash
          colcon build --symlink-install
          . install/local_setup.bash

      - name: Colcon Test power_energy_propogation
        run: |
          colcon test --packages-select power_energy_propogation
          colcon test-result --all --verbose

  cppcheck:
    name: Cppcheck
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Cppcheck
        run: sudo apt install cppcheck -y
      
      - name: Run Cppcheck
        run: cppcheck .

  mypy:
    name: Mypy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Mypy
        run: pip install mypy
      
      - name: Run Mypy
        run: |
          cd power_energy_propogation
          python3 -m mypy .

  pydocstyle:
    name: Pydocstyle
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Pydocstyle
        run: pip install pydocstyle
      
      - name: Run Pydocstyle
        run: |
          cd power_energy_propogation
          python3 -m pydocstyle .

  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Flake8
        run: pip install flake8
      
      - name: Run Flake8
        run: |
          cd power_energy_propogation
          python3 -m flake8 .
