BatteryLevel[] charge_levels # list of battery soc and power level
float64[] external_signal # list of external power signal
float64[] resulting_signal # list of resulting power signal
float64[] primary_fitness_history 
float64[] secondary_fitness_history
float64[] tertiary_fitness_history
int32[] time_idxs # list of times in minutes
int32 min_time_idx # min time index
int32 max_time_idx # max time index
int32 planner_num # planner number

